### ISSUE TITLE
How can I plot a custom list of labels onto the chart?

### ISSUE THREAD

**Issue by GoChartingAdmin** [GoChartingAdmin/Go-Charting#16]
I have a curated list of timestamped news items, and I'd like to overlay it onto the chart, the way Google Finance does that with news.

Does GoCharting support this?

**Comment by GoChartingAdmin** [comment]
I do not think we should have a problem developing this feature. Queries:
1. Do you want the user to come with their own list of news with timestamp? If yes, how would our app get the feed? For example upload a csv or call anu API?
2. We provide google news today.  Would you want the same plotted on the chart?  This is relatively easy to deploy as we already have the feed

Let us know

**Comment by GoChartingAdmin** [comment]
We are revamping our newsroom next week and your request will be a part of it.

**Comment by GoChartingAdmin** [comment]
This goes live today

![image](https://user-images.githubusercontent.com/20324844/37866240-5d7b3d52-2f88-11e8-9b70-2903264e991b.png)

**Comment by Bomper** [comment]
That looks neat. I'm also interested in this feature. How do I use it? Where is your documentation?

https://gocharting.com/widgets shows some HTML code to paste. Where is the API to supply an array of news markers?
