### ISSUE TITLE
Scrollbar 

### ISSUE THREAD

**Issue by GoChartingAdmin** [GoChartingAdmin/Go-Charting#44]
https://github.com/rrag/react-stockcharts/issues/614

**Comment by benmccann** [comment]
When I move my mouse to the right side of the screen the scrollbar does not appear like I would expect (i.e. like the native scrollbar would). It also seems like it has an acceleration / momentum that is very different than the standard scrollbar and thus does not work as I'd expect. I would prefer the native scrollbar and don't see much benefit from having one that is different

Below is a screenshot of what happens on my computer. My mouse is all the way on the righthand side of the screen barely visible and yet the scrollbar is still not appearing

![screenshot from 2018-08-13 06-49-11](https://user-images.githubusercontent.com/322311/44035785-257db34c-9ec5-11e8-8b71-dd37e1d7aa98.png)

**Comment by GoChartingAdmin** [comment]
Got it.  We will fix it coming weekend

**Comment by GoChartingAdmin** [comment]
Fixed.  Thank you for bringing this to our notice

**Comment by benmccann** [comment]
Thanks! Much easier to use now!
